apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: api-deployment    
  name: api-service
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
    nodePort: 30000
  selector:
    app: api-deployment
  type: NodePort
status:
  loadBalancer: {}