apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: api
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - image: dianapatru/movierecommender-api:2.0
        name: api
        ports:
        - containerPort: 8000
        envFrom:
          - secretRef:
              name: database-secret
          - configMapRef:
              name: app-configmap
         