apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: business-deployment    
  name: business-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: business-deployment
status:
  loadBalancer: {}