apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: database-deployment
  name: database-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database-deployment
  template:
    metadata:
      labels:
        app: database-deployment
    spec:
      containers:
      - image: dianapatru/movierecommender-database:1.0
        name: database-deployment
        volumeMounts:
          - name: database-volume
            mountPath: /var/lib/postgresql/data
        ports:
        - containerPort: 5432
        envFrom:
          - secretRef:
              name: database-secret
      volumes:
        - name: database-volume
          persistentVolumeClaim:
            claimName: postgres-pvc