apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: database-service
  labels:
    app: database-deployment
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: database-deployment
status:
  loadBalancer: {}