apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rabbitmq-deployment
  name: rabbitmq-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq-deployment
  template:
    metadata:
      labels:
        app: rabbitmq-deployment
    spec:
      containers:
      - image: rabbitmq:3
        name: rabbitmq-deployment
        ports:
        - containerPort: 5672