version: '3'

services:
  api:
    image: api:latest
    environment:
      PORT: 8000
      AMQPURL: amqp://rabbitmq
    restart: on-failure
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3
    