FROM python:latest

WORKDIR /RecommenderSystem

COPY requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt

COPY ./src ./src
COPY ./scripts/ ./scripts
COPY Makefile Makefile

RUN ./scripts/download_dataset.sh
RUN cd ./src
 
CMD ["make"]